module.exports = {
  PROJECTNAME: 'PROJECTNAME',
  TEMPDIR: 'TEMPDIR',
  CLEANUPTEMPDIR: 'CLEANUPTEMPDIR',
  CONTAINERMODE: 'CONTAINERMODE',
  STARTCMD: 'STARTCMD',
  DOCKERCOMPOSEPATH: 'DOCKERCOMPOSEPATH',
  DOCKERIMAGE: 'DOCKERIMAGE',
  DOCKERSYSLOGPORT: 'DOCKERSYSLOGPORT',
  // Facebook Mocker Settings
  FACEBOOK_API: 'FACEBOOK_API',
  FACEBOOK_WEBHOOK_PORT: 'FACEBOOK_WEBHOOK_PORT',
  FACEBOOK_WEBHOOK_PATH: 'FACEBOOK_WEBHOOK_PATH',
  FACEBOOK_PUBLISHPORT: 'FACEBOOK_PUBLISHPORT',
  // Slack Mocker Settings
  SLACK_API: 'SLACK_API',
  // Bot Framework Mocker Settings
  BOTFRAMEWORK_API: 'BOTFRAMEWORK_API'
}
