module.exports = {
  CONTAINERMODE: 'CONTAINERMODE',
  STARTCMD: 'STARTCMD',
  DOCKERCOMPOSEPATH: 'DOCKERCOMPOSEPATH',
  DOCKERIMAGE: 'DOCKERIMAGE',
  DOCKERTEMP: 'DOCKERTEMP',
  // Facebook Mocker Settings
  FACEBOOK_API: 'FACEBOOK_API',
  FACEBOOK_WEBHOOK_PORT: 'FACEBOOK_WEBHOOK_PORT',
  FACEBOOK_WEBHOOK_PATH: 'FACEBOOK_WEBHOOK_PATH',
  // Slack Mocker Settings
  SLACK_API: 'SLACK_API',
  // Bot Framework Mocker Settings
  BOTFRAMEWORK_API: 'BOTFRAMEWORK_API'
}
